// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Statesman.Outbox.EntityFrameworkCore;

#nullable disable

namespace Statesman.Outbox.EntityFrameworkCore.Sqlite.Migrations
{
    [DbContext(typeof(StatesmanOutboxCursorDbContext))]
    partial class StatesmanOutboxCursorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Statesman.Outbox.EntityFrameworkCore.StatesmanOutboxCursorEntity", b =>
                {
                    b.Property<string>("OutboxId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("OutboxId");

                    b.ToTable("StatesmanOutboxCursors", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
