// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Statesman;

#nullable disable

namespace Statesman.Persistence.EntityFrameworkCore.Sqlite.Migrations
{
    [DbContext(typeof(StatesmanLedgerDbContext))]
    partial class StatesmanLedgerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Statesman.StatesmanLedgerHead", b =>
                {
                    b.Property<string>("Root")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Partition")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CausationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FreshUntil")
                        .HasColumnType("TEXT");

                    b.Property<long>("GlobalPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Operation")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Payload")
                        .HasColumnType("BLOB");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ServeUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Root", "Path", "Partition");

                    b.ToTable("StatesmanHeads", (string)null);
                });

            modelBuilder.Entity("Statesman.StatesmanLedgerLease", b =>
                {
                    b.Property<string>("LeaseId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("LeaseId");

                    b.ToTable("StatesmanLeases", (string)null);
                });

            modelBuilder.Entity("Statesman.StatesmanLedgerRecord", b =>
                {
                    b.Property<string>("Root")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Partition")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CausationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FreshUntil")
                        .HasColumnType("TEXT");

                    b.Property<long>("GlobalPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Operation")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Payload")
                        .HasColumnType("BLOB");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ServeUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Root", "Path", "Partition", "Revision");

                    b.HasIndex("GlobalPosition")
                        .IsUnique();

                    b.ToTable("StatesmanRecords", (string)null);
                });

            modelBuilder.Entity("Statesman.StatesmanLedgerSequence", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Value")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("StatesmanSequences", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
