// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Statesman.Outbox.EntityFrameworkCore;

#nullable disable

namespace Statesman.Outbox.EntityFrameworkCore.PostgreSql.Migrations
{
    [DbContext(typeof(StatesmanOutboxCursorDbContext))]
    partial class StatesmanOutboxCursorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Statesman.Outbox.EntityFrameworkCore.StatesmanOutboxCursorEntity", b =>
                {
                    b.Property<string>("OutboxId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.HasKey("OutboxId");

                    b.ToTable("StatesmanOutboxCursors", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
