<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/Statesman/Statesman.csproj" />
    <ProjectReference Include="../../src/Statesman.Persistence.EntityFrameworkCore/Statesman.Persistence.EntityFrameworkCore.csproj" />
    <ProjectReference Include="../../src/Statesman.Persistence.FileSystem/Statesman.Persistence.FileSystem.csproj" />
    <ProjectReference Include="../../src/Statesman.Persistence.Redis/Statesman.Persistence.Redis.csproj" />
    <ProjectReference Include="../../src/Statesman.Persistence.Tiered/Statesman.Persistence.Tiered.csproj" />
    <ProjectReference Include="../../src/Statesman.Testing/Statesman.Testing.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../Shared/PausingTimeProvider.cs" Link="PausingTimeProvider.cs" />
  </ItemGroup>
</Project>
