// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Statesman;

#nullable disable

namespace Statesman.Persistence.EntityFrameworkCore.SqlServer.Migrations
{
    [DbContext(typeof(StatesmanLedgerDbContext))]
    [Migration("20260912020701_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Statesman.StatesmanLedgerHead", b =>
                {
                    b.Property<string>("Root")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Partition")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CausationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("FreshUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("GlobalPosition")
                        .HasColumnType("bigint");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<byte[]>("Payload")
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ServeUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Root", "Path", "Partition");

                    b.ToTable("StatesmanHeads", (string)null);
                });

            modelBuilder.Entity("Statesman.StatesmanLedgerLease", b =>
                {
                    b.Property<string>("LeaseId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("LeaseId");

                    b.ToTable("StatesmanLeases", (string)null);
                });

            modelBuilder.Entity("Statesman.StatesmanLedgerRecord", b =>
                {
                    b.Property<string>("Root")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Partition")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<string>("CausationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("FreshUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("GlobalPosition")
                        .HasColumnType("bigint");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<byte[]>("Payload")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ServeUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Root", "Path", "Partition", "Revision");

                    b.HasIndex("GlobalPosition")
                        .IsUnique();

                    b.ToTable("StatesmanRecords", (string)null);
                });

            modelBuilder.Entity("Statesman.StatesmanLedgerSequence", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("Value")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Name");

                    b.ToTable("StatesmanSequences", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
