// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Statesman.Outbox.EntityFrameworkCore;

#nullable disable

namespace Statesman.Outbox.EntityFrameworkCore.SqlServer.Migrations
{
    [DbContext(typeof(StatesmanOutboxCursorDbContext))]
    [Migration("20260912021856_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Statesman.Outbox.EntityFrameworkCore.StatesmanOutboxCursorEntity", b =>
                {
                    b.Property<string>("OutboxId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.HasKey("OutboxId");

                    b.ToTable("StatesmanOutboxCursors", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
