<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../../src/Statesman.AspNetCore/Statesman.AspNetCore.csproj" />
    <ProjectReference Include="../../src/Statesman.Extensions.DependencyInjection/Statesman.Extensions.DependencyInjection.csproj" />
    <ProjectReference Include="../../src/Statesman.Testing/Statesman.Testing.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
  </ItemGroup>
</Project>
