<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Statesman/Statesman.csproj" />
    <ProjectReference Include="../../src/Statesman.Testing/Statesman.Testing.csproj" />
  </ItemGroup>
</Project>
