<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Statesman.Extensions.DependencyInjection/Statesman.Extensions.DependencyInjection.csproj" />
    <ProjectReference Include="../../src/Statesman.Extensions.Hosting/Statesman.Extensions.Hosting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
</Project>
